# Generated by Django 5.0.3 on 2024-03-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('photo', models.ImageField(upload_to='cinema_django/images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.country')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('photo', models.ImageField(upload_to='cinema_django/images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.country')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('rating', models.FloatField()),
                ('photo', models.ImageField(upload_to='cinema_django/images/')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.actor')),
                ('genre', models.ManyToManyField(to='catalog.genre')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], default='Available', max_length=50)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.film')),
            ],
        ),
    ]
