# Generated by Django 5.0.3 on 2024-03-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_producer_pseudonym_remove_session_due_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='actors',
            new_name='actor',
        ),
    ]
